### PR TITLE
Args by names and new Operators XOR, NAND, IN, NOT IN, REGEX-MATCH, REGEX-UNMATCH

### PR DESCRIPTION
**Pull request by vjeantet**
Feel free to pick, reject :) my implementation may be naive or sub optimized.

### CODE REVIEW

**Comment by vjeantet** [comment]
here is the new kind to expression that can be evaluated
```
[foo] in [foobar]
[foo] not in [foobar]
[foo] not in ["bonjour", "le monde", "oui"]
[foo] in [2,3,4]
[foo] =~ /^5\\d\\d/
[status] !~ /^4\\d\\d/
```

**Comment by oleksandr** [comment]
@vjeantet Thanks, these pretty cool features, also the expression format is not backwards compatible (but it's worth to pay that price). I've noticed you've also extended govaluate, which is very close to this library. I'm curious how do you find the difference between them? What made you consider the conditions as well?

**Comment by vjeantet** [comment]
I was looking if a existing package could fit my needs. I found yours and extended it. When i found govaluate, i choose to extend it too, because the extended implementation is similar.

To be honest, i'm still reviewing the two, i care more about code readability than perf.

**Comment by oleksandr** [comment]
Cool. Well, this lib is rather a shameless lending from InfluxDB code :-) After all, http://www.amazon.de/gp/product/B0074QGGK6/ ;-)

**Pull request merged**
